sudo: required
dist: trusty
group: edge

services:
  - rabbitmq
language: python
python:
  - "3.5"
install:
  - pip install codecov
jobs:
  include:
  - stage: test
    script: docker build -f Dockerfile.base .
  - script: python3 setup.py install
before_install:
  - sudo apt-get update
  - sudo apt-get install docker-ce
after_success:
  - codecov
